import React, { ReactNode } from "react";
import {
  HiOutlineBan,
  HiOutlineBookOpen,
  HiOutlineChartPie,
  HiOutlineChartSquareBar,
  HiOutlineChatAlt,
  HiOutlineCode,
  HiOutlineColorSwatch,
  HiOutlineCurrencyDollar,
  HiOutlineDesktopComputer,
  HiOutlineDocumentDuplicate,
  HiOutlineDocumentText,
  HiOutlineHand,
  HiOutlineKey,
  HiOutlineLockClosed,
  HiOutlinePaperAirplane,
  HiOutlineShare,
  HiOutlineShieldCheck,
  HiOutlineTemplate,
  HiOutlineTrendingUp,
  HiOutlineUserAdd,
  HiOutlineUserCircle,
  HiOutlineUserGroup,
  HiOutlineVariable,
  HiOutlineViewGridAdd,
} from "react-icons/hi";

const navigationIcon: Record<string, ReactNode> = {
  apps: <HiOutlineViewGridAdd />,
  project: <HiOutlineChartSquareBar />,
  crm: <HiOutlineUserGroup />,
  sales: <HiOutlineTrendingUp />,
  crypto: <HiOutlineCurrencyDollar />,
  knowledgeBase: <HiOutlineBookOpen />,
  account: <HiOutlineUserCircle />,
  uiComponents: <HiOutlineTemplate />,
  common: <HiOutlineColorSwatch />,
  feedback: <HiOutlineChatAlt />,
  dataDisplay: <HiOutlineDesktopComputer />,
  forms: <HiOutlineDocumentText />,
  navigation: <HiOutlinePaperAirplane />,
  graph: <HiOutlineChartPie />,
  authentication: <HiOutlineLockClosed />,
  signIn: <HiOutlineShieldCheck />,
  signUp: <HiOutlineUserAdd />,
  forgotPassword: <HiOutlineLockClosed />,
  resetPassword: <HiOutlineKey />,
  pages: <HiOutlineDocumentDuplicate />,
  welcome: <HiOutlineHand />,
  accessDenied: <HiOutlineBan />,
  guide: <HiOutlineBookOpen />,
  documentation: <HiOutlineDocumentText />,
  sharedComponentDoc: <HiOutlineShare />,
  utilsDoc: <HiOutlineVariable />,
  changeLog: <HiOutlineCode />,
};

export default navigationIcon;
